INSERT INTO USER_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES (1, 'abc@gmail.com', 'abc employee', '936738227', 'abc');

INSERT INTO USER_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES (2, 'xyz@gmail.com', 'xyz employee', '964772667', 'xyz');